<?php 

 $wysiwyg = array (
  'comment' => 
  array (
    'format' => 'comment',
    'editor' => 'tinymce',
    'settings' => 
    array (
      'default' => 1,
      'user_choose' => 0,
      'show_toggle' => 0,
      'theme' => 'advanced',
      'language' => 'en',
      'buttons' => 
      array (
        'default' => 
        array (
          'bold' => 1,
          'italic' => 1,
          'link' => 1,
          'unlink' => 1,
          'removeformat' => 1,
        ),
        'inlinepopups' => 
        array (
          'inlinepopups' => 1,
        ),
        'autoresize' => 
        array (
          'autoresize' => 1,
        ),
        'paste' => 
        array (
          'paste' => 1,
        ),
      ),
      'toolbar_loc' => 'top',
      'toolbar_align' => 'left',
      'path_loc' => 'bottom',
      'resizing' => 1,
      'verify_html' => 1,
      'preformatted' => 0,
      'convert_fonts_to_spans' => 1,
      'remove_linebreaks' => 0,
      'apply_source_formatting' => 0,
      'paste_auto_cleanup_on_paste' => 1,
      'block_formats' => 'p',
      'css_setting' => 'self',
      'css_path' => '',
      'css_classes' => '',
    ),
    'rdf_mapping' => 
    array (
    ),
  ),
  'default' => 
  array (
    'format' => 'default',
    'editor' => 'tinymce',
    'settings' => 
    array (
      'default' => 1,
      'user_choose' => 0,
      'show_toggle' => 0,
      'theme' => 'advanced',
      'language' => 'en',
      'buttons' => 
      array (
        'default' => 
        array (
          'bold' => 1,
          'italic' => 1,
          'bullist' => 1,
          'numlist' => 1,
          'link' => 1,
          'unlink' => 1,
          'removeformat' => 1,
        ),
        'font' => 
        array (
          'formatselect' => 1,
          'styleselect' => 1,
        ),
        'inlinepopups' => 
        array (
          'inlinepopups' => 1,
        ),
        'autoresize' => 
        array (
          'autoresize' => 1,
        ),
        'drupal' => 
        array (
          'media' => 1,
        ),
      ),
      'toolbar_loc' => 'top',
      'toolbar_align' => 'left',
      'path_loc' => 'bottom',
      'resizing' => 1,
      'verify_html' => 1,
      'preformatted' => 0,
      'convert_fonts_to_spans' => 1,
      'remove_linebreaks' => 0,
      'apply_source_formatting' => 0,
      'paste_auto_cleanup_on_paste' => 1,
      'block_formats' => 'p,h2,h3,h4',
      'css_setting' => 'self',
      'css_path' => '',
      'css_classes' => '',
    ),
    'rdf_mapping' => 
    array (
    ),
  ),
);

