<?php
/**
 * @file
 * Code for the Tiles Demo feature.
 */

include_once 'ombudemo_base.features.inc';

/**
 * Implements hook_tiles_widths().
 */
function ombudemo_base_tiles_widths() {
  return array(
    'ombucleanup' => array(
      'site_logo' => 2,
    ),
    'menu' => array(
      'header-menu' => 6,
    ),
    'search' => array(
      'form' => 4,
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ombudemo_base_form_search_block_form_alter(&$form, $form_state) {
  $form['#attributes']['class'][] = 'navbar-form';
  $form['#attributes']['class'][] = 'navbar-right';
}

/**
 * Implements hook_preprocess_block().
 */
function ombudemo_base_preprocess_block(&$variables) {
  if ($variables['block']->module == 'search') {
    $variables['classes_array'][] = 'navbar-right';
  }
}

/**
 * Implements hook_bean_style_options_alter().
 */
function ombudemo_base_bean_style_options_alter(&$options, $context) {
  // Remove all but bootstrap slideshow for demo purposes.
  if ($context['bundle'] == 'ombuslide') {
    foreach ($options as $key => $value) {
      if ($key != 'bootstrap_slideshow') {
        unset($options[$key]);
      }
    }
  }
}
