<?php
/**
 * @file
 * Code for the Tiles Demo feature.
 */

include_once 'ombudemo_base.features.inc';

/**
 * Implements hook_tiles_widths().
 */
function ombudemo_base_tiles_widths() {
  return array(
    'ombucleanup' => array(
      'site_logo' => 2,
    ),
    'menu' => array(
      'header-menu' => 6,
    ),
    'search' => array(
      'form' => 4,
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ombudemo_base_form_search_block_form_alter(&$form, $form_state) {
  $form['#attributes']['class'][] = 'navbar-form';
}

/**
 * Implements hook_preprocess_block().
 */
function ombudemo_base_preprocess_block(&$variables) {
  if ($variables['block']->module == 'search') {
    $variables['classes_array'][] = 'navbar-right';
  }
}
